document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("	<meta charset=\"utf-8\">");
document.writeln("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
document.writeln("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js\" integrity=\"sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r\" crossorigin=\"anonymous\"></script>");
document.writeln("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js\" integrity=\"sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy\" crossorigin=\"anonymous\"></script>");
document.writeln("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">");
document.writeln("    <link href=\"core.css\" rel=\"stylesheet\">");
document.writeln("    <style type=\"text/css\">");
document.writeln("      .b {background:#f5f6fa;padding:20px 10%;width:100%;} ");
document.writeln("      .a {background:#224b77;color:white;text-align:center;line-height:300%;font-size:13px;}");
document.writeln("      .col-lg-4 {text-align: center;}");
document.writeln("      .eessd h2 {margin-top:32px;font-weight:bold;font-size:26px;}");
document.writeln("      jsf {font-size:18px;font-weight:normal;}");
document.writeln("      jsk {font-size:15px;}");
document.writeln("        @media (max-width: 961px) {");
document.writeln("          div.col-1 {display: none;}");
document.writeln("}");
document.writeln("    </style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div class=\"b row\">");
document.writeln("  <div class=\"col-lg-4\"><br><img src=\"https://13511974.s21i.faiusr.com/2/10/ABUIABACGAAgoeeyrwYo6NqPqAMwlgE4lgE.jpg\" height=\"140px\" style=\"border-radius:200px;\"></div>");
document.writeln("  <div class=\"col-1\"><img src=\"https://13511974.s21i.faiusr.com/4/10/ABUIABAEGAAg9YazrwYo5NvvlQcwfziaAw.png\" height=\"200px\" width=\"2px\"></div>");
document.writeln("  <div class=\"col-lg-3 eessd\"><h2>Yang Shihe\'s Blog<br><jsf>技术、生活与分享</jsf></h2><h3><jsk>个人博客地址：https://www.yangshihe.com/<br>E-mail：hello@yangshihe.com</jsk></h3></div>");
document.writeln("</div>");
document.writeln("<div class=\"a\">");
document.writeln("  © 2024 Yangshihe.com");
document.writeln("</div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");
