document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("	<meta charset=\"utf-8\">");
document.writeln("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
document.writeln("	<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js\" integrity=\"sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r\" crossorigin=\"anonymous\"></script>");
document.writeln("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js\" integrity=\"sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy\" crossorigin=\"anonymous\"></script>");
document.writeln("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">");
document.writeln("    <link href=\"core.css\" rel=\"stylesheet\">");
document.writeln("    <style type=\"text/css\">");
document.writeln("    	.fye a {color:#228fbd;text-decoration: none;margin-top:20px;}");
document.writeln("    	.fye a:hover {text-decoration:underline;color:#000;}");
document.writeln("    </style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<div class=\"qbwz_bt\"><b>全部文章</b></div>");
document.writeln("<div class=\"qbwz_zw\">");
document.writeln("	");
document.writeln("	<div class=\"wzzy\" onclick=\"window.location.href=\'b-a-1\'\">");
document.writeln("		<h2><wzzybt>入门c语言：高速公路超速处罚</wzzybt><br><wzzyzy>摘要：无</wzzyzy><wzzyrq>2023-09-21</wzzyrq></h2>");
document.writeln("	</div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<p class=\"fye\" style=\"text-align: center;\"><a href=\"#\">Prev</a>&nbsp&nbsp<a href=\"#\">1</a>&nbsp&nbsp<a href=\"#\">Next</a></p>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("</html>");
