document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("  <title>Bootstrap5 实例</title>");
document.writeln("  <meta charset=\"utf-8\">");
document.writeln("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
document.writeln("  <link href=\"\" rel=\"stylesheet\">");
document.writeln("  <script src=\"https://cdn.staticfile.net/twitter-bootstrap/5.1.1/js/bootstrap.bundle.min.js\"></script>");
document.writeln("  <style type=\"text/css\">");
document.writeln("    .payzsn {color:#fff;background:#DF0029;padding:0px 15px;line-height:220%;font-size:15px;border:none;border-radius:8px;}");
document.writeln("    p {text-align: center;}");
document.writeln("  </style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<p><button class=\"payzsn\" data-bs-toggle=\"collapse\" data-bs-target=\"#demo\">打赏本文</button></p>");
document.writeln("<div id=\"demo\" class=\"collapse\">");
document.writeln("<p><img src=\"#\" width=\"200px\"><br>不支持</p>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("</html>");