document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("  <title>Bootstrap5 实例</title>");
document.writeln("  <meta charset=\"utf-8\">");
document.writeln("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
document.writeln("  <link href=\"\" rel=\"stylesheet\">");
document.writeln("  <script src=\"https://cdn.staticfile.net/twitter-bootstrap/5.1.1/js/bootstrap.bundle.min.js\"></script>");
document.writeln("  <style type=\"text/css\">");
document.writeln("    .payzsn {color:#fff;background:#DF0029;padding:0px 15px;line-height:220%;font-size:15px;border:none;border-radius:9px}");
document.writeln("    p {text-align: center;}");
document.writeln("    .wrhrs {border-radius:0;border: none;background:none;}");
document.writeln("    .cisfaf {padding:0;background:none;text-align:center;}");
document.writeln("  </style>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<p><button class=\"payzsn\" data-bs-toggle=\"modal\" data-bs-target=\"#myModal\">赞赏本文</button></p>");
document.writeln("<!-- 模态框 -->");
document.writeln("<div class=\"modal\" id=\"myModal\">");
document.writeln("  <div class=\"modal-dialog\">");
document.writeln("    <div class=\"modal-content wrhrs\">");
document.writeln(" ");
document.writeln("      <!-- 模态框内容 -->");
document.writeln("      <div class=\"modal-body cisfaf\">");
document.writeln("       <img src=\"https://13511974.s21i.faiusr.com/4/10/ABUIABAEGAAgvOC2rwYoqIvUswYwlwk4lwk.png\" width=\"100%\"><br><br><button class=\"btn-close bg-light\" data-bs-dismiss=\"modal\" style=\"padding:10px;border-radius:100px;\"></button>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("</div>");
document.writeln("</body>");
document.writeln("</html>");
