document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("	<meta charset=\"utf-8\">");
document.writeln("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
document.writeln("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js\" integrity=\"sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r\" crossorigin=\"anonymous\"></script>");
document.writeln("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js\" integrity=\"sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy\" crossorigin=\"anonymous\"></script>");
document.writeln("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">");
document.writeln("    <link href=\"core.css\" rel=\"stylesheet\">");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<nav class=\"navbar navbar-expand-lg navbar-dark\">");
document.writeln("  <a class=\"navbar-brand touxiang\" href=\"/\"><img src=\"https://13511974.s21i.faiusr.com/2/10/ABUIABACGAAgoeeyrwYo6NqPqAMwlgE4lgE.jpg\" height=\"40px\" style=\"border-radius:100px;\"></a>");
document.writeln("    <a class=\"navbar-brand biaoti\" href=\"/\">YANG SHIHE</a>");
document.writeln("  <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#navbarOffcanvasLg\" aria-controls=\"navbarOffcanvasLg\" aria-label=\"Toggle navigation\">");
document.writeln("    <span class=\"navbar-toggler-icon\"></span>");
document.writeln("  </button>");
document.writeln("  <div class=\"offcanvas offcanvas-end\" id=\"navbarOffcanvasLg\" aria-labelledby=\"navbarOffcanvasLgLabel\">");
document.writeln("      <div class=\"offcanvas-header\">");
document.writeln("        <button type=\"button\" class=\"btn-close btn bg-light\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>");
document.writeln("      </div>");
document.writeln("      <div class=\"offcanvas-body\">");
document.writeln("        <ul class=\"navbar-nav justify-content-end \">");
document.writeln("          <li class=\"nav-item\">");
document.writeln("            <a class=\"nav-link\" href=\"/\">首页</a>");
document.writeln("          </li>");
document.writeln("          ");
document.writeln("          <li class=\"nav-item dropdown\">");
document.writeln("            <a class=\"nav-link dropdown-toggle\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">");
document.writeln("              文章分类");
document.writeln("            </a>");
document.writeln("            <ul class=\"dropdown-menu\">");
document.writeln("              <li><a class=\"dropdown-item\" href=\"/b-a-all\">全部</a></li>");
document.writeln("              <li><a class=\"dropdown-item\" href=\"#\">日期归档2023-08</a></li>");
document.writeln("              <li><a class=\"dropdown-item\" href=\"#\">日期归档2023-09</a></li>");
document.writeln("              <li><a class=\"dropdown-item\" href=\"#\">日期归档2023-10</a></li>");
document.writeln("              <li><a class=\"dropdown-item\" href=\"#\">日期归档2023-11</a></li>");
document.writeln("              <li><a class=\"dropdown-item\" href=\"#\">日期归档2023-12</a></li>");
document.writeln("              <li><a class=\"dropdown-item\" href=\"#\">日期归档2024-01</a></li>");
document.writeln("              <li><a class=\"dropdown-item\" href=\"#\">日期归档2024-02</a></li>");
document.writeln("              <li><a class=\"dropdown-item\" href=\"#\">日期归档2024-03</a></li>");
document.writeln("              <li><a class=\"dropdown-item\" href=\"#\">日期归档2024-04</a></li>");
document.writeln("             ");
document.writeln("            </ul>");
document.writeln("          </li>");
document.writeln("          <li class=\"nav-item\">");
document.writeln("            <a class=\"nav-link\" href=\"/b-a-7\">域名出售</a>");
document.writeln("          </li>");
document.writeln("        </ul>");
document.writeln("        ");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("</nav>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");
